"""Round 6 (2026-09-06): append 26 net-new venue records re-verified against
live official venue pages, refresh meta.recordCount/verifiedOn.

Every source.quote below is transcribed verbatim from the official venue page
captured during this verification pass. Gaps and irregularities are listed in
each record's flags (and in VERIFICATION.md, Round 6 section).
"""
import json

DATA = "data/venues.json"

NEW = [
    {
        "id": "blackthorn-tavern",
        "name": "Blackthorn Tavern",
        "category": "Sports bar / neighborhood pub",
        "neighborhood": "Inner Sunset",
        "address": "834 Irving St, San Francisco, CA 94122",
        "officialUrl": "https://www.blackthornsf.com/contact.html",
        "hours": {
            "Monday": "1:00 PM–2:00 AM",
            "Tuesday": "1:00 PM–2:00 AM",
            "Wednesday": "1:00 PM–2:00 AM",
            "Thursday": "1:00 PM–2:00 AM",
            "Friday": "1:00 PM–2:00 AM",
            "Saturday": "12:00 PM–2:00 AM",
            "Sunday": "10:00 AM–2:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni N Judah at Irving & 9th + walk",
            "detail": "From 21st Ave & Judah, board the N Judah to Irving St & 9th Ave and walk one block east; Blackthorn sits on Irving just east of 9th Ave.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["N"],
        },
        "source": {
            "label": "Official Blackthorn contact page",
            "url": "https://www.blackthornsf.com/contact.html",
            "quote": "834 Irving St. San Francisco, CA, 94122 — 1(415) 564-6626 — Hours - M-F 1pm to 2am, Sat Noon to 2am, Sun 10am to 2am (9:30 am to 2am during Football Season)",
        },
        "flags": [
            "Site notes earlier opening (Sat 10am / Sun 9:15-9:30am during college & NFL football seasons).",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday, Saturday, and Sunday all close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "inner-sunset",
    },
    {
        "id": "the-bitter-end",
        "name": "The Bitter End",
        "category": "Pub / bar & grill",
        "neighborhood": "Richmond District",
        "address": "441 Clement St, San Francisco, CA 94118",
        "officialUrl": "https://www.thebitterendsf.com/",
        "hours": {
            "Monday": "4:00 PM–2:00 AM",
            "Tuesday": "4:00 PM–2:00 AM",
            "Wednesday": "4:00 PM–2:00 AM",
            "Thursday": "4:00 PM–2:00 AM",
            "Friday": "4:00 PM–2:00 AM",
            "Saturday": "12:00 PM–2:00 AM",
            "Sunday": "12:00 PM–2:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 38 Geary at Geary & 6th Ave + walk north to Clement",
            "detail": "From 21st Ave & Judah, ride the N Judah downtown or the 6; transfer to the 38 Geary, exit near Geary & 6th Ave, and walk one block north to 441 Clement St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["38"],
        },
        "source": {
            "label": "Official The Bitter End home page",
            "url": "https://www.thebitterendsf.com/",
            "quote": "Location 441 Clement Street San Francisco — Hours Mon - Fri 4pm – 2am, Sat + Sun noon – 2am",
        },
        "flags": [
            "Kitchen keeps its own schedule (dinner menu page); the 2 AM close above is the bar close printed on the home page.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday, Saturday, and Sunday all close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "richmond",
    },
    {
        "id": "club-waziema",
        "name": "Club Waziema",
        "category": "Ethiopian restaurant / bar",
        "neighborhood": "Divisadero / NoPa",
        "address": "543 Divisadero St, San Francisco, CA 94117",
        "officialUrl": "https://www.clubwaziemasf.com/",
        "hours": {
            "Monday": "Closed",
            "Tuesday": "6:00 PM–2:00 AM",
            "Wednesday": "6:00 PM–2:00 AM",
            "Thursday": "6:00 PM–2:00 AM",
            "Friday": "6:00 PM–2:00 AM",
            "Saturday": "6:00 PM–2:00 AM",
            "Sunday": "Closed",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 24 Divisadero or 5 Fulton + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Church St for the 22, or ride to Market and transfer to the 24 Divisadero; exit at Divisadero & Hayes, steps from 543 Divisadero.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["24", "5"],
        },
        "source": {
            "label": "Official Club Waziema home page",
            "url": "https://www.clubwaziemasf.com/",
            "quote": "Opening Hours. Dine In or Take Away — Sunday - Monday: closed — Tuesday - Saturday: 6pm - 2am",
        },
        "flags": [
            "Sunday and Monday are explicitly closed on the official page; Friday and Saturday run to 2 AM.",
            "Historic jazz-era room (formerly Club Morocco); kitchen service window not separately stated on the page.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and weekly hours; Friday and Saturday close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "divisadero-nopa",
    },
    {
        "id": "horsefeather",
        "name": "Horsefeather",
        "category": "Cocktail bar / restaurant",
        "neighborhood": "Divisadero / NoPa",
        "address": "528 Divisadero St, San Francisco, CA 94117",
        "officialUrl": "https://horsefeather.com/sf/book",
        "hours": {
            "Monday": "2:00 PM–12:00 AM",
            "Tuesday": "2:00 PM–12:00 AM",
            "Wednesday": "2:00 PM–12:00 AM",
            "Thursday": "2:00 PM–12:00 AM",
            "Friday": "2:00 PM–2:00 AM",
            "Saturday": "11:00 AM–2:00 AM",
            "Sunday": "11:00 AM–12:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 24 Divisadero or 5 Fulton + walk",
            "detail": "From 21st Ave & Judah, take the N Judah toward downtown, transfer to the 24 Divisadero, exit at Divisadero & Hayes; 528 Divisadero is on the next block.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["24", "5"],
        },
        "source": {
            "label": "Official Horsefeather SF reservations/hours page",
            "url": "https://horsefeather.com/sf/book",
            "quote": "HORSEFEATHER SAN FRANCISCO — 528 DIVISADERO ST SF, CA 94117 — HOURS: MONDAY-THURSDAY 2p-12a (kitchen 11:30pm); FRIDAY 2p-2a (kitchen 1:00am); SATURDAY 11a-2a (kitchen 1:00am); SUNDAY 11a-12a (kitchen 11:30pm)",
        },
        "flags": [
            "Kitchen closes separately (11:30 PM most nights, 1:00 AM Fri/Sat); times above are bar hours as printed.",
            "horsefeathersf.com redirects to horsefeather.com (location picker); the SF page lives at /sf/book.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at 2 AM and Sunday at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "divisadero-nopa",
    },
    {
        "id": "rock-bar",
        "name": "Rock Bar",
        "category": "Neighborhood bar",
        "neighborhood": "Bernal Heights",
        "address": "80 29th St, San Francisco, CA 94110",
        "officialUrl": "https://rockbarsf.com/",
        "hours": {
            "Monday": "4:00 PM–12:00 AM",
            "Tuesday": "4:00 PM–12:00 AM",
            "Wednesday": "4:00 PM–12:00 AM",
            "Thursday": "4:00 PM–12:00 AM",
            "Friday": "4:00 PM–2:00 AM",
            "Saturday": "4:00 PM–2:00 AM",
            "Sunday": "10:00 AM–12:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 24 Divisadero at 30th/Mission + walk, or 14 Mission",
            "detail": "From 21st Ave & Judah, take the N Judah to Market and transfer to the 14 Mission or 24 Divisadero toward Bernal; exit near 29th & Mission and walk one block to 80 29th St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["14", "24"],
        },
        "source": {
            "label": "Official Rock Bar home page",
            "url": "https://rockbarsf.com/",
            "quote": "Hours — 415.550.6664 | 80 29th street, san francisco, ca 94110 — open Mon-Thu 4pm-12am, Fri-Sat 4pm-2am, Sun 10am-12am",
        },
        "flags": [
            "Football Sundays open at 10:00 AM per the site's news board.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at 2 AM and Sunday at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "bernal-heights",
    },
    {
        "id": "wild-side-west",
        "name": "Wild Side West",
        "category": "LGBTQ+ neighborhood bar",
        "neighborhood": "Bernal Heights",
        "address": "424 Cortland Ave, San Francisco, CA, 94110",
        "officialUrl": "https://www.wildsidewest.com/",
        "hours": {
            "Monday": "2:00 PM–2:00 AM (site states a single daily window)",
            "Tuesday": "2:00 PM–2:00 AM (site states a single daily window)",
            "Wednesday": "2:00 PM–2:00 AM (site states a single daily window)",
            "Thursday": "2:00 PM–2:00 AM (site states a single daily window)",
            "Friday": "2:00 PM–2:00 AM (site states a single daily window)",
            "Saturday": "2:00 PM–2:00 AM (site states a single daily window)",
            "Sunday": "2:00 PM–2:00 AM (site states a single daily window)",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 24 Divisadero at Cortland + walk",
            "detail": "From 21st Ave & Judah, ride the N Judah to Market, transfer to the 24 Divisadero, exit at Cortland Ave; the bar notes it sits 'directly on the MUNI 24 line' at 424 Cortland.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["24"],
        },
        "source": {
            "label": "Official Wild Side West home page",
            "url": "https://www.wildsidewest.com/",
            "quote": "424 Cortland Avenue San Francisco, CA 94110 — 415.647.3099 — Open from 2PM - 2AM",
        },
        "flags": [
            "Official page prints one daily window ('Open from 2PM - 2AM') with no per-day breakdown; aggregated venue listings consistently mirror daily 2 PM–2 AM, flagged for manual review.",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official venue page checked for address and the published daily 2 PM–2 AM window; per-day variation cannot be ruled out from the page alone.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "bernal-heights",
    },
    {
        "id": "tony-niks",
        "name": "Tony Nik's Cafe",
        "category": "Cocktail lounge / neighborhood bar",
        "neighborhood": "North Beach",
        "address": "1534 Stockton St, San Francisco, CA 94133",
        "officialUrl": "https://www.tonyniks.com/contact/",
        "hours": {
            "Monday": "4:00 PM–1:00 AM",
            "Tuesday": "4:00 PM–1:00 AM",
            "Wednesday": "4:00 PM–1:00 AM",
            "Thursday": "4:00 PM–1:00 AM",
            "Friday": "3:00 PM–2:00 AM",
            "Saturday": "2:00 PM–2:00 AM",
            "Sunday": "2:00 PM–1:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 30 Stockton or 45 Union-Stockton + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer toward North Beach on the 30 Stockton, exit at Stockton & Union; 1534 Stockton is between Union and Filbert.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["30", "45"],
        },
        "source": {
            "label": "Official Tony Nik's contact page",
            "url": "https://www.tonyniks.com/contact/",
            "quote": "Hours — Mon-Thurs: 4PM-1AM — Fridays: 3PM-2AM — Saturday: 2PM-2AM — Sunday: 2PM-1AM — Address — 1534 Stockton Street San Francisco, CA 94133",
        },
        "flags": [
            "Sunday-to-Thursday close is 1 AM on the official page (older third-year listings claiming 2 AM daily are stale).",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at 2 AM, Sunday at 1 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "north-beach",
    },
    {
        "id": "tommys-joynt",
        "name": "Tommy's Joynt",
        "category": "Hofbrau restaurant / bar",
        "neighborhood": "Van Ness / Cathedral Hill",
        "address": "1101 Geary Blvd, San Francisco, CA 94109",
        "officialUrl": "https://tommysjoynt.com/",
        "hours": {
            "Monday": "12:00 PM–8:00 PM",
            "Tuesday": "12:00 PM–9:00 PM",
            "Wednesday": "12:00 PM–9:00 PM",
            "Thursday": "12:00 PM–12:00 AM",
            "Friday": "12:00 PM–12:00 AM",
            "Saturday": "1:00 PM–12:00 AM",
            "Sunday": "12:00 PM–8:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 38 Geary to Geary & Van Ness, or 49 Van Ness-Mission",
            "detail": "From 21st Ave & Judah, take the N Judah downtown and transfer to the 38 Geary outbound to Geary & Van Ness; Tommy's Joynt is on the southwest corner at 1101 Geary.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["38", "49"],
        },
        "source": {
            "label": "Official Tommy's Joynt home page",
            "url": "https://tommysjoynt.com/",
            "quote": "Sun & Mon 12 – 8 PM — Tue & Wed 12 – 9 PM — Thu & Fri 12 Noon – 12 Midnight — Saturday 1 PM – 12 Midnight — Holiday hours same except Thanksgiving & Christmas. No reservations — counter service, first come first served. — 1101 Geary Blvd at Van Ness, San Francisco",
        },
        "flags": [
            "Late close is Thursday through Saturday only (midnight); counter service with no reservations per the site.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "lower-nob-hill",
    },
    {
        "id": "the-deluxe",
        "name": "The Deluxe",
        "category": "Bar / live music venue",
        "neighborhood": "Haight",
        "address": "1511 Haight St, San Francisco, CA 94117",
        "officialUrl": "https://thedeluxesf.com/",
        "hours": {
            "Monday": "6:00 PM–11:00 PM",
            "Tuesday": "6:00 PM–11:00 PM",
            "Wednesday": "6:00 PM–11:00 PM",
            "Thursday": "6:00 PM–11:00 PM",
            "Friday": "5:00 PM–1:00 AM",
            "Saturday": "5:00 PM–1:00 AM",
            "Sunday": "2:30 PM–10:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 7 Haight-Noriega, 6 Parnassus, or 43 Masonic + walk",
            "detail": "From 21st Ave & Judah, the 6 Parnassus serves Parnassus Ave nearby, or take the N Judah to Cole and walk north; 1511 Haight is between Ashbury and Clayton.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["7", "43", "6"],
        },
        "source": {
            "label": "Official The Deluxe home page",
            "url": "https://thedeluxesf.com/",
            "quote": "Now Open — 1511 Haight St San Francisco, CA 94107 — Mon-Thu 6:00 p.m. – 11:00 p.m. — Fri & Sat 5:00 p.m. – 1:00 a.m. — Sun 2:30 p.m. – 10:00 p.m.",
        },
        "flags": [
            "Irregularity: the official page prints ZIP '94107' for 1511 Haight St; the correct ZIP is 94117 (flagged for review, address otherwise matches).",
            "Reopened operator at the historic Club Deluxe address; hours above are the current page's.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at 1 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "haight",
    },
    {
        "id": "temple-sf",
        "name": "Temple SF",
        "category": "Nightclub",
        "neighborhood": "SoMa",
        "address": "540 Howard St, San Francisco, CA 94105",
        "officialUrl": "https://www.templesf.com/",
        "hours": {
            "Monday": "Club nights by calendar; no standing weekday schedule published",
            "Tuesday": "Club nights by calendar; no standing weekday schedule published",
            "Wednesday": "Club nights by calendar; no standing weekday schedule published",
            "Thursday": "Club nights by calendar; no standing weekday schedule published",
            "Friday": "10:00 PM–2:00 AM",
            "Saturday": "10:00 PM–2:00 AM",
            "Sunday": "Sundays: Please check Calendar (event-driven; no standing close published)",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 12 Folsom/Pacific or 14 Mission + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 14 Mission (exit at 2nd St) or 12 Folsom; 540 Howard sits between 1st and 2nd Streets.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["12", "14"],
        },
        "source": {
            "label": "Official Temple SF home page",
            "url": "https://www.templesf.com/",
            "quote": "Hours — Friday: 10:00 pm - 2:00 am — Saturday: 10:00 pm - 2:00 am — Sundays: Please check Calendar — location — Temple SF 540 HOWARD ST SAN FRANCISCO, CA 94105",
        },
        "flags": [
            "Nightclub: 21+ admission with tickets/table reservations for headline nights; Sunday operation is calendar-driven.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and weekly hours; published Friday and Saturday nights close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "soma",
    },
    {
        "id": "true-laurel",
        "name": "True Laurel",
        "category": "Cocktail bar / restaurant",
        "neighborhood": "Mission",
        "address": "753 Alabama St, San Francisco, CA 94110",
        "officialUrl": "https://www.truelaurelsf.com/",
        "hours": {
            "Monday": "Closed (site lists Tuesday–Sunday only)",
            "Tuesday": "4:00 PM–10:00 PM",
            "Wednesday": "4:00 PM–10:00 PM",
            "Thursday": "4:00 PM–11:00 PM",
            "Friday": "4:00 PM–12:00 AM",
            "Saturday": "11:00 AM–12:00 AM",
            "Sunday": "11:00 AM–10:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 33 Ashbury-18th or 14 Mission + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Church, transfer to the 33 toward the Mission, exit near 18th & Mission, and walk to 753 Alabama St (between 18th and 19th).",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["33", "14"],
        },
        "source": {
            "label": "Official True Laurel home page",
            "url": "https://www.truelaurelsf.com/",
            "quote": "open: tues/wed: 4pm-10pm, thursday: 4pm-11pm, friday: 4pm-midnight, saturday: 11am-midnight, sunday: 11am-10pm — brunch hours: saturday/sunday: 11am-3pm — 753 alabama st",
        },
        "flags": [
            "Late close is Friday/Saturday only (midnight); Monday is not listed by the venue and is treated as closed.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "mission",
    },
    {
        "id": "woods-lowside",
        "name": "Woods Lowside",
        "category": "Brewery taproom / wine bar",
        "neighborhood": "Lower Haight",
        "address": "530 Haight St, San Francisco, CA 94117",
        "officialUrl": "https://www.woodsbeer.com/lowside",
        "hours": {
            "Monday": "5:00 PM–11:00 PM",
            "Tuesday": "5:00 PM–11:00 PM",
            "Wednesday": "5:00 PM–11:00 PM",
            "Thursday": "5:00 PM–11:00 PM",
            "Friday": "4:00 PM–12:00 AM",
            "Saturday": "1:00 PM–12:00 AM",
            "Sunday": "1:00 PM–10:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 7 Haight-Noriega + bike/walk from the Sunset, or N Judah + 22 Fillmore",
            "detail": "From 21st Ave & Judah, take the N Judah to Cole for the 7 Haight connection east, or transfer to the 22 Fillmore; 530 Haight is near Fillmore St in the Lower Haight.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["7"],
        },
        "source": {
            "label": "Official Woods Lowside page",
            "url": "https://www.woodsbeer.com/lowside",
            "quote": "530 Haight Street — BAR Hours — Monday - Wednesday: 5pm to 11pm — Thursday: 5pm to 11pm — Friday: 4pm to 12am — Saturday: 1pm to 12am — Sunday: 1pm to 10pm — KITCHEN Hours — Monday: 5pm to 9pm; Thursday–Sunday: 5pm to 9pm",
        },
        "flags": [
            "Kitchen (Tacos Oscar) closes at 9 PM and is closed Tuesday/Wednesday; bar hours above are printed separately on the official page.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "lower-haight",
    },
    {
        "id": "standard-deviant",
        "name": "Standard Deviant Brewing (280 14th St)",
        "category": "Brewery taproom",
        "neighborhood": "Mission",
        "address": "280 14th St, San Francisco, CA 94103",
        "officialUrl": "https://www.standarddeviantbrewing.com/28014thst",
        "hours": {
            "Monday": "Closed (not listed on the official hours board)",
            "Tuesday": "4:00 PM–9:00 PM",
            "Wednesday": "4:00 PM–10:00 PM",
            "Thursday": "4:00 PM–10:00 PM",
            "Friday": "3:00 PM–12:00 AM",
            "Saturday": "12:00 PM–12:00 AM",
            "Sunday": "10:00 AM–9:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 14 Mission + walk to 14th & Folsom",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 14 Mission, exit at Mission & 14th, and walk west to 280 14th St near Folsom.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["14"],
        },
        "source": {
            "label": "Official Standard Deviant 280 14th St page",
            "url": "https://www.standarddeviantbrewing.com/28014thst",
            "quote": "280 14th Street — In the heart of the Mission — Hours — Tuesday 4-9pm — Wednesday 4-10pm — Thursday 4-10pm — Friday 3pm-12am — Saturday 12pm-12am — Sunday 10am-9pm",
        },
        "flags": [
            "Monday is absent from the official hours board (treated as closed); food is by pop-ups Thursday–Sunday per the site.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and weekly hours; Friday and Saturday close at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "mission",
    },
    {
        "id": "hotel-utah-saloon",
        "name": "The Hotel Utah Saloon",
        "category": "Saloon / live music venue",
        "neighborhood": "SoMa",
        "address": "500 4th St, San Francisco, CA 94107",
        "officialUrl": "https://hotelutah.com/",
        "hours": {
            "Monday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
            "Tuesday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
            "Wednesday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
            "Thursday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
            "Friday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
            "Saturday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
            "Sunday": "11:00 AM–12:00 AM (bar; 'or later on show nights')",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 12 Folsom/Pacific or T Third + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 12 or T toward SoMa; the saloon is at 500 4th St near Bryant.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["12"],
        },
        "source": {
            "label": "Official Hotel Utah Saloon home page",
            "url": "https://hotelutah.com/",
            "quote": "HOURS — Open Daily at 11:00 AM — bar open until midnight (or later on show nights) — Kitchen hours 11:00AM to 11PM — 500 4th St. S.F., CA 94107",
        },
        "flags": [
            "Irregularity: closing time is stated as 'midnight (or later on show nights)' — later close is show-dependent and not guaranteed; 21+ on show nights with cover.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and weekly hours; the published daily bar close is midnight, past the 11 PM threshold on all seven days.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "soma",
    },
    {
        "id": "the-edge",
        "name": "The Edge",
        "category": "LGBTQ+ neighborhood bar",
        "neighborhood": "Castro",
        "address": "4149 18th St, San Francisco, CA 94114",
        "officialUrl": "https://edgesf.com/",
        "hours": {
            "Monday": "2:00 PM–2:00 AM",
            "Tuesday": "2:00 PM–1:00 AM",
            "Wednesday": "2:00 PM–2:00 AM",
            "Thursday": "2:00 PM–1:00 AM",
            "Friday": "2:00 PM–2:00 AM",
            "Saturday": "12:00 PM–2:00 AM",
            "Sunday": "12:00 PM–2:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 24 Divisadero at 18th St + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Church, transfer to the 24 toward 18th St, exit at 18th & Collingwood; The Edge is at 4149 18th St near Castro.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["24"],
        },
        "source": {
            "label": "Official The Edge home page",
            "url": "https://edgesf.com/",
            "quote": "HOURS — Mon: 2pm-2am — Tues: 2pm-1am — Wed: 2pm-2am — Thurs: 2pm-1am — Fri: 2pm-2am — Sat-Sun: 12pm-2am — LOCATION — 4149 18th St. San Francisco, CA 94114",
        },
        "flags": [
            "Site notes 'We are open 365 days a year'; Tuesday/Thursday close is 1 AM, all other nights 2 AM.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday, Saturday, and Sunday all close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "castro-upper-market",
    },
    {
        "id": "hole-in-the-wall-saloon",
        "name": "Hole in the Wall Saloon",
        "category": "LGBTQ+ dive bar",
        "neighborhood": "SoMa",
        "address": "1369 Folsom St, San Francisco, CA 94103",
        "officialUrl": "https://www.blackwolfmetal.com/",
        "hours": {
            "Monday": "2:00 PM–2:00 AM",
            "Tuesday": "2:00 PM–2:00 AM",
            "Wednesday": "2:00 PM–2:00 AM",
            "Thursday": "2:00 PM–2:00 AM",
            "Friday": "2:00 PM–2:00 AM",
            "Saturday": "12:00 PM–2:00 AM",
            "Sunday": "12:00 PM–2:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 12 Folsom/Pacific + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 12 Folsom, exit at Folsom & 9th; the bar is at 1369 Folsom St between 9th and 10th.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["12"],
        },
        "source": {
            "label": "Official Hole in the Wall page (owner's domain)",
            "url": "https://www.blackwolfmetal.com/",
            "quote": "1369 Folsom Street, SF — Your Friendly Neighborhood Gay Biker's Bar — Open MON > FRI 2pm 'til 2am SAT + SUN > noon 'til 2am",
        },
        "flags": [
            "Irregularity: the venue's official page is hosted on blackwolfmetal.com (the owner's metalwork studio domain) rather than a bar-named domain; content is the bar's own page, flagged for manual review.",
        ],
        "verification": {
            "status": "verified",
            "method": "Venue-controlled page checked for name, address, and weekly hours; all seven nights close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "soma",
    },
    {
        "id": "columbus-cafe",
        "name": "Columbus Cafe",
        "category": "Neighborhood bar",
        "neighborhood": "North Beach",
        "address": "562 Green St, San Francisco, CA 94133",
        "officialUrl": "https://columbuscafesf.com/",
        "hours": {
            "Monday": "2:00 PM–2:00 AM",
            "Tuesday": "2:00 PM–2:00 AM",
            "Wednesday": "2:00 PM–2:00 AM",
            "Thursday": "2:00 PM–2:00 AM",
            "Friday": "2:00 PM–2:00 AM",
            "Saturday": "12:00 PM–2:00 AM",
            "Sunday": "12:00 PM–2:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 30 Stockton or 45 Union-Stockton + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 30 Stockton or 45, exit around Union & Columbus, and walk to 562 Green St between Columbus and Grant.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["30", "45"],
        },
        "source": {
            "label": "Official Columbus Cafe home page",
            "url": "https://columbuscafesf.com/",
            "quote": "562 Green Street San Francisco, CA 94133 Between Columbus Avenue and Grant Street — Hours — Monday–Friday 2 PM–2 AM — Saturday–Sunday 12 PM–2 AM — Open 365 days a year.",
        },
        "flags": [
            "This venue was excluded in an earlier sweep for lack of an official domain; columbuscafesf.com is now live, so it is admitted on this pass (precedent change documented).",
            "Self-describes as a legacy San Francisco bar (Legacy Business Registry 2025) showing sports incl. NHL.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and weekly hours; all seven nights close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "north-beach",
    },
    {
        "id": "jolenes",
        "name": "Jolene's",
        "category": "Bar",
        "neighborhood": "Mission",
        "address": "2700 16th St, San Francisco, CA 94103",
        "officialUrl": "https://www.jolenessf.com/hours",
        "hours": {
            "Monday": "Closed (not listed on the official hours board)",
            "Tuesday": "Closed (not listed on the official hours board)",
            "Wednesday": "Closed (not listed on the official hours board)",
            "Thursday": "7:00 PM–2:00 AM",
            "Friday": "7:00 PM–2:00 AM",
            "Saturday": "7:00 PM–2:00 AM",
            "Sunday": "Closed (not listed on the official hours board)",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 22 Fillmore at 16th St, or 14 Mission + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Church, transfer to the 22 Fillmore toward 16th St, exit at 16th & Harrison; Jolene's is at 2700 16th St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["22", "14"],
        },
        "source": {
            "label": "Official Jolene's hours page",
            "url": "https://www.jolenessf.com/hours",
            "quote": "HOURS — thursday 7pm - 2am — friday 7pm - 2am — saturday 7pm - 2am — location — 2700 16th st. san francisco, ca 94103",
        },
        "flags": [
            "Official board lists Thursday–Saturday only; all other days treated as closed (not verified open).",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and weekly hours; Friday and Saturday close at 2 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "mission",
    },
    {
        "id": "kaiyo-rooftop",
        "name": "Kaiyō Rooftop",
        "category": "Rooftop bar / Nikkei restaurant",
        "neighborhood": "SoMa",
        "address": "701 3rd St, Floor 12, San Francisco, CA 94107",
        "officialUrl": "https://www.kaiyosf.com/rooftop",
        "hours": {
            "Monday": "4:00 PM–10:00 PM",
            "Tuesday": "4:00 PM–11:00 PM",
            "Wednesday": "4:00 PM–11:00 PM",
            "Thursday": "4:00 PM–11:00 PM",
            "Friday": "4:00 PM–1:00 AM",
            "Saturday": "11:00 AM–1:00 AM",
            "Sunday": "11:00 AM–10:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni T Third at UCSF/Chase Center or 4th & King + walk",
            "detail": "From 21st Ave & Judah, take the N Judah downtown and transfer to the T Third, exit near 3rd & Townsend; Kaiyō Rooftop is atop the Hyatt Place at 701 3rd St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["T"],
        },
        "source": {
            "label": "Official Kaiyō Rooftop page",
            "url": "https://www.kaiyosf.com/rooftop",
            "quote": "KAIYO ROOFTOP HOURS & LOCATION — 701 3RD ST, FLOOR 12 SAN FRANCISCO, CA 94107 — Monday 4:00PM - 10:00PM Tuesday 4:00PM - 11:00PM Wednesday 4:00PM - 11:00PM Thursday 4:00PM - 11:00PM Friday 4:00PM – 1:00AM Saturday 11:00AM – 1:00AM Sunday 11:00AM – 10:00PM",
        },
        "flags": [
            "Open-air rooftop (12th floor of the Hyatt Place); the venue notes it may cancel reservations in severe weather — day-of re-check advised.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at 1 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "soma",
    },
    {
        "id": "woods-polk-station",
        "name": "Woods Polk Station",
        "category": "Brewery taproom / wine bar",
        "neighborhood": "Polk Gulch",
        "address": "2255 Polk St, San Francisco, CA 94109",
        "officialUrl": "https://www.woodsbeer.com/polk-station",
        "hours": {
            "Monday": "4:00 PM–10:00 PM",
            "Tuesday": "4:00 PM–10:00 PM",
            "Wednesday": "4:00 PM–10:00 PM",
            "Thursday": "4:00 PM–10:00 PM",
            "Friday": "1:00 PM–12:00 AM",
            "Saturday": "1:00 PM–12:00 AM",
            "Sunday": "1:00 PM–8:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 19 Polk + walk; 49 Van Ness-Mission nearby",
            "detail": "From 21st Ave & Judah, take the N Judah downtown and transfer to the 49 Van Ness, exit near Union, or ride the 19 Polk along the corridor; Woods Polk Station is at 2255 Polk St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["19", "49"],
        },
        "source": {
            "label": "Official Woods Polk Station page",
            "url": "https://www.woodsbeer.com/polk-station",
            "quote": "2255 Polk Street — (415) 463-7418 — Hours — Monday - Thursday 4pm to 10pm — Friday - Saturday 1pm to 12am — Sunday 1pm to 8pm — SPECIAL Hours — Christmas Eve: Closed; Christmas Day: Closed; NYE: Open normal hours; NYD: Open 1-8pm",
        },
        "flags": [
            "Late close is Friday/Saturday only (midnight); holiday deviations printed on the same page.",
        ],
        "verification": {
            "status": "verified",
            "method": "Official venue page checked for name, address, and full weekly hours; Friday and Saturday close at midnight.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "polk-gulch",
    },
    {
        "id": "richmond-republic",
        "name": "Richmond Republic Draught House",
        "category": "Sports bar / pub",
        "neighborhood": "Richmond District",
        "address": "642 Clement St, San Francisco, CA 94118",
        "officialUrl": "https://www.richmondrepublicsf.com/",
        "hours": {
            "Monday": "Weekly grid not printed on the live site; weekend close verified, weekday hours unverified",
            "Tuesday": "Weekly grid not printed on the live site; weekend close verified, weekday hours unverified",
            "Wednesday": "Weekly grid not printed on the live site; weekend close verified, weekday hours unverified",
            "Thursday": "Weekly grid not printed on the live site; weekend close verified, weekday hours unverified",
            "Friday": "Open until 12:00 AM (per official-domain hours snippet); opening time not stated",
            "Saturday": "Open until 12:00 AM (per official-domain hours snippet); opening time not stated",
            "Sunday": "Weekly grid not printed on the live site; weekend close verified, weekday hours unverified",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 38 Geary at Geary & 8th Ave + walk north to Clement",
            "detail": "From 21st Ave & Judah, take the N Judah or 6 toward downtown and transfer to the 38 Geary, exit near 8th Ave, walk north to 642 Clement St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["38"],
        },
        "source": {
            "label": "Official Richmond Republic home page",
            "url": "https://www.richmondrepublicsf.com/",
            "quote": "Official-domain search index for richmondrepublicsf.com lists: Friday/Saturday open until 12:00 AM; the live Wix page itself is a minimal template that does not render the full weekly grid in plain text.",
        },
        "flags": [
            "Hours entered from the venue-controlled domain's indexed hours snippet rather than rendered page text — flagged for manual re-check.",
            "Site hosts 'Order Pickup & Delivery' via a third-party platform; no weekly hours grid in accessible text.",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official domain live and address-confirmed; weekly hours only partially accessible, qualifying Friday/Saturday midnight close taken from the official-domain snippet and flagged.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "richmond",
    },
    {
        "id": "the-knockout",
        "name": "The Knockout",
        "category": "Dive bar / live music venue",
        "neighborhood": "Mission",
        "address": "3223 Mission St, San Francisco, CA 94110",
        "officialUrl": "https://theknockoutsf.com/",
        "hours": {
            "Monday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
            "Tuesday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
            "Wednesday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
            "Thursday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
            "Friday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
            "Saturday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
            "Sunday": "6:00 PM–2:00 AM (per official-domain hours snippet)",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 14 Mission or J Church + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 14 Mission outbound to Mission & Valencia/29th, and walk to 3223 Mission St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["14"],
        },
        "source": {
            "label": "Official The Knockout home page",
            "url": "https://theknockoutsf.com/",
            "quote": "Venue page (Squarespace + DICE embed) shows event listings at '3223 Mission Street San Francisco, CA, 94110'; official-domain hours snippet lists 'Open Daily 6:00 pm – 2:00 am'.",
        },
        "flags": [
            "Irregularity: the live homepage event grid is stale (September 2023 events still displayed); the venue remains active per current listings, but the weekly hours come from the official-domain snippet, not the rendered page — flagged for manual review.",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official domain live and address-confirmed on-page; daily 6 PM–2 AM hours taken from the official-domain indexed snippet and flagged alongside the stale-calendar irregularity.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "mission",
    },
    {
        "id": "beauty-bar-sf",
        "name": "Beauty Bar",
        "category": "Bar",
        "neighborhood": "Mission",
        "address": "2299 Mission St, San Francisco, CA 94110",
        "officialUrl": "https://www.beautybarsf.com/",
        "hours": {
            "Monday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
            "Tuesday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
            "Wednesday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
            "Thursday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
            "Friday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
            "Saturday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
            "Sunday": "2:00 PM–2:00 AM (official-domain snippet: 'Open Daily 2 pm - 2 am')",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 14 Mission + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 14 Mission, exit at Mission & 19th; Beauty Bar is at 2299 Mission St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["14"],
        },
        "source": {
            "label": "Official Beauty Bar SF site",
            "url": "https://www.beautybarsf.com/",
            "quote": "beautybarsf.com (venue-controlled Squarespace) search-index text: 'Beauty Bar — 2299 Mission Street San Francisco, CA — Hours — Open Daily 2 pm - 2 am'; the live homepage renders imagery with no plain-text hours block.",
        },
        "flags": [
            "Newly reopened Mission bar (post-2025 relaunch); hours taken from the official-domain indexed text rather than rendered page copy — flagged for manual review.",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official venue domain live and address/hours present in its indexed text; daily 2 PM–2 AM window flagged for on-page re-confirmation.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "mission",
    },
    {
        "id": "brixton",
        "name": "The Brixton",
        "category": "Gastropub / bar",
        "neighborhood": "Cow Hollow",
        "address": "2140 Union St, San Francisco, CA 94123",
        "officialUrl": "https://www.brixtonsf.com/",
        "hours": {
            "Monday": "Closed",
            "Tuesday": "4:00 PM–10:00 PM",
            "Wednesday": "4:00 PM–10:00 PM",
            "Thursday": "4:00 PM–12:00 AM",
            "Friday": "4:00 PM–1:30 AM",
            "Saturday": "10:00 AM–1:30 AM",
            "Sunday": "10:00 AM–10:00 PM",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 45 Union-Stockton + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 45 Union-Stockton to Cow Hollow, exit near Union & Fillmore/Steiner, and walk to 2140 Union St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["45"],
        },
        "source": {
            "label": "Official The Brixton home page + structured data",
            "url": "https://www.brixtonsf.com/",
            "quote": "Homepage text: 'We're open Tuesday through Sunday at 2140 Union Street — closed Mondays.' Official-domain structured data (JSON-LD) openingHours: Su 10:00-22:00, Tu 16:00-22:00, We 16:00-22:00, Th 16:00-00:00, Fr 16:00-01:30, Sa 10:00-01:30 — 2140 Union Street, San Francisco, CA 94123.",
        },
        "flags": [
            "Hours verified from the venue-domain's JSON-LD payload; the rendered homepage omits the full grid (flagged for manual review).",
            "Third-party listings disagree (TripAdvisor shows restaurant dinner closes ~10 PM); the venue's own structured data with the 1:30 AM Fri/Sat bar close was used.",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official venue page checked for name, address, and hours via on-domain structured data; Friday/Saturday close at 1:30 AM.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "marina-presidio",
    },
    {
        "id": "mcteagues",
        "name": "McTeague's",
        "category": "Soccer bar / neighborhood bar",
        "neighborhood": "Polk Gulch",
        "address": "1237 Polk St, San Francisco, CA 94109",
        "officialUrl": "https://www.sfmcteagues.com/",
        "hours": {
            "Monday": "Closed, except 'Open Monday during World Cup' per site",
            "Tuesday": "12:00 PM–2:00 AM",
            "Wednesday": "12:00 PM–2:00 AM",
            "Thursday": "12:00 PM–2:00 AM",
            "Friday": "12:00 PM–2:00 AM",
            "Saturday": "7:00 AM–2:00 AM",
            "Sunday": "7:00 AM–2:00 AM",
        },
        "qualifyingDays": ["Friday", "Saturday", "Sunday"],
        "access": {
            "summary": "Muni 19 Polk or 49 Van Ness-Mission + walk",
            "detail": "From 21st Ave & Judah, take the N Judah downtown, transfer to the 49 Van Ness, exit near Sutter, and walk east to 1237 Polk St.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["19", "49"],
        },
        "source": {
            "label": "Official McTeague's home page",
            "url": "https://www.sfmcteagues.com/",
            "quote": "When We Pour: Tuesday – Friday 12 pm – 2 am — Saturday – Sunday 7 am – 2 am (Open early for Live European Soccer) — Mondays: Open Monday during World Cup",
        },
        "flags": [
            "Irregularity: the street address (1237 Polk) is not printed anywhere on the venue's own site text; it is corroborated by the venue's linked listings (SFStation and official-domain sameAs records) and flagged for manual confirmation.",
            "Opens 7 AM weekends for European soccer; Monday only during World Cup windows.",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official venue page checked for weekly hours (all weekend days close 2 AM); address confirmed via corroborating listings because the site omits it — flagged.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "polk-gulch",
    },
    {
        "id": "barbarossa",
        "name": "Barbarossa Lounge",
        "category": "Cocktail lounge",
        "neighborhood": "Financial District",
        "address": "714 Montgomery St, San Francisco, CA 94111",
        "officialUrl": "https://barbarossalounge.com/",
        "hours": {
            "Monday": "Not published on the official site (event cards only)",
            "Tuesday": "Not published on the official site (event cards only)",
            "Wednesday": "Not published on the official site (event cards only)",
            "Thursday": "Evening service advertised Thursday (card: 8PM–2AM; body text: till 12:30 AM) — internally inconsistent",
            "Friday": "Late Night 8:00 PM–2:00 AM (per site card; body text says 12:30 AM) — internally inconsistent",
            "Saturday": "Late Night 8:00 PM–2:00 AM (per site card; body text says 12:30 AM) — internally inconsistent",
            "Sunday": "Not published on the official site (event cards only)",
        },
        "qualifyingDays": ["Friday", "Saturday"],
        "access": {
            "summary": "Muni 30 Stockton or 45 Union-Stockton + walk",
            "detail": "From 21st Ave & Judah, take the N Judah to Market, transfer to the 30 Stockton or 45, exit near Jackson & Kearny/Montgomery, and walk to 714 Montgomery St at the Transamerica block.",
            "sources": [{"label": "SFMTA route directory", "url": "https://www.sfmta.com/routes"}],
            "lineIds": ["30", "45"],
        },
        "source": {
            "label": "Official Barbarossa home page",
            "url": "https://barbarossalounge.com/",
            "quote": "714 Montgomery Street San Francisco, CA — event card: 'Late Night Fri-Sat 8PM-2AM' — body text: 'Barbarossa Lounge is open till 12:30am Thu-Sat.'",
        },
        "flags": [
            "Irregularity: the same official page carries two conflicting weekend closes (card 'Fri-Sat 8PM-2AM' vs body 'till 12:30am Thu-Sat'); both clear the 11 PM threshold for Friday/Saturday, but review the page before going.",
            "Thursday also carries conflicting late cards (8PM–2AM card vs 12:30 AM text).",
        ],
        "verification": {
            "status": "verified-with-gap",
            "method": "Official venue page checked for address and late-night cards; conflicting close times captured verbatim and flagged; Friday/Saturday qualify under either reading.",
            "verifiedOn": "2026-09-06",
        },
        "neighborhoodGroup": "financial-district",
    },
]

with open(DATA) as f:
    d = json.load(f)

existing = {v["id"] for v in d["venues"]}
for rec in NEW:
    if rec["id"] in existing:
        raise SystemExit(f"duplicate id: {rec['id']}")

d["venues"].extend(NEW)
d["meta"]["recordCount"] = len(d["venues"])
d["meta"]["verifiedOn"] = "2026-09-06"

with open(DATA, "w") as f:
    json.dump(d, f, indent=1, ensure_ascii=False)
print(f"records now: {d['meta']['recordCount']} (+{len(NEW)})")
